server:
  port: 8088
spring:
  datasource:
#    jdbc:mysql://localhost:3307/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    encoding: UTF-8
    basename: i18n/messages
    default-locale: en
api:
  prefix: api/v1

jwt:
  expiration: 2592000
  secretKey: CGfanE4+YnKLDi+tnBsmGIw1x4JBnyIHiQ7/wxLeof0=

logging.level.org.springframework.security: DEBUG
